### PR TITLE
Update: HSQ questions init data

### PR DESCRIPTION
**Pull request by haanh764**
Hello, this PR aims to update the questions for Humor Style Questionnaire.

What's changed:
- `backend/questionnaires/migrations/0003_initial.py`: update migration file for initial questions for HSQ questionnaire
- `backend/questionnaires/migrations/0007_auto_20230309_1630.py`: add function `update_humor_style_questionnaire()` to update HSQ questions

### CODE REVIEW

**Review by teddy-f-47 — APPROVED** [review]
Thank you for the quick update. Approved!

**Review by artikandri — APPROVED** [review]
Hello, thank you for the update. For our note here, I will check the frontend side to see if I need to adjust the questions to follow this, because right now I think the frontend is matching the questions by the text content. Approved!

**Comment by haanh764** [comment]
Hello, I've tested again with production env in my computer and as Piotr said last time it's correct that if I change the init migration files, it could be not updated and required delete the whole table to migrate again. Since when we run migration there is nothing change in the model, but only changes in data. I forgot that case :sweat_smile: 

Therefore, I created a new migration file to alter the rows needed to be update and replace those rows with new data. Then when we deploy the new version, the `python manage.py migrate` will recognize the new file to be migrated and execute the changes.

**Review by teddy-f-47 — APPROVED** [review]
I have tested the recent change and it now works properly. Thank you for the great work, approved! :)

**Comment by artikandri** [comment]
Thank you for the changes xD  I have tested it as well and it works, so approved :3

**Review by artikandri — APPROVED** [review]

**Pull request merged**
