### PR TITLE
Fix: FE - Questionnaire bugs, styling

### PR DESCRIPTION
**Pull request by artikandri**
Features added with this PR: 
- Fix the bugs when two users logged in with the same browser with the addition of `userHistory` attribute
- Check lastLoginTime validity and reset all questionnaires when the login time is not valid 
- Time checking & form showing bugs
- Simple styling 

What's changed: 
- `frontend/components/auth/FormLogin.vue`: added lastLoginTime check, adjusted the functions to deal with user/store new structure
- `frontend/components/questionnaires/GreetingCard.vue`: styling
- `frontend/components/questionnaires/QuestionnaireForm.vue`: styling, fixed some bugs
- `frontend/components/questionnaires/form/DynamicSelectInput.vue`: additional  required check by filtering empty strings
- `frontend/components/questionnaires/form/*Input.vue`: styling
- `frontend/store/user.js`: adjusted the structure to deal with multiple users logging in with the same browser
- `frontend/utils/questionnaires.js`: added new function to check valid login time
- `frontend/pages/questionnaires/*/js/questionnaires.js`: numericOnly check in structure 
- `frontend/pages/questionnaires/index.vue`: styling 
- `frontend/components/questionnaires/form/TextInput.vue`: minor alignment, passedData fix 

Screenshots: 
Screenshot from 2022-09-09 22-12-43
image

### CODE REVIEW

**Review by teddy-f-47 — APPROVED** [review]
Thank you for the great work! I think it is also important to note that an annotator must always use the same device and browser, because otherwise if they use a different device or browser then their questionnaire history won't be available and they will need to do the questionnaires from zero (which will also overwrite the saved answers in db) -- to solve this we will need to somehow save the annotator's questionnaires history in BE. But I think our current solution should suffice for the pilot study, we just need to tell the annotators to use the same device and browser to do the work. Approved for merging!

**Review by haanh764 — COMMENTED** [review]
Hello, thank you so much for the great work! I have tested and everything looks good, and the functionalities mostly work well also. 
Only 1 problem with the Ankieta zwrotna. This Ankieta zwrotna will appear 1st time after 1 week of the annotation procedure, but now for me after the 1st week it wasn't shown (I changed the date to 12/12, 13/12. 15/2 also). And it showed up if I changed the date to 3/3/2023 (3 months from my 1st working day) even I haven't finished all of my project, but it's just for your info because it's pretty minor thing since the user will have to finish their work before that time. And also the main flow and logic of the questionnaires at the end of procedure are oke so it's not a problem, just fyi. So could you please check if that Ankieta zwrotna doesn't show after the 1st week of annotation procedure or it's only my computer's problem :sweat_smile:

**Comment by teddy-f-47** [comment]
> So could you please check if that Ankieta zwrotna doesn't show after the 1st week of annotation procedure or it's only my computer's problem 😅

Hello, I have added the fix. Now the Ankieta Zwrotna should appear both after 1 week and after the end of the research. A notable thing that I have noticed in my computer though, when changing the date manually for testing, sometimes the changed date does not immediatelly propagate to the browser, in which case a few refresh or navigating between pages may be necessary. However, in real use, I believe it won't be an issue XD

**Review by haanh764 — APPROVED** [review]
Hello, thank you for your quick fix XD I have tested again and everything works well. Approved!

**Pull request merged**
