### PR TITLE
Feat: New endpoint for logging timestamp when annotator start annotate 1 example

### PR DESCRIPTION
**Pull request by haanh764**
What's changed:

- `backend/examples/models.py`: added new model for logging state of starting annotation time
- `backend/examples/serializers.py`: added new serializer for model `ExampleAnnotateStartState`
- `backend/examples/views/example_state.py`: added new view for new state logging
- `backend/examples/urls.py`: added new endpoint for new state logging

The new endpoint for logging the starting annotation time for each example is `/v1/projects/4/examples/3315/annotate_start_states`

Note: Last time, I said that I will use the current table `ExampleState` for logging this starting annotation state, but there is a constraint about the confirm person and then I changed my mind that we should separate it to 2 different tables (this way is clearer and cleaner I think). Then later we can combine data from these 2 tables easily. So now we have 2 tables, 'ExampleState' is for keeping the time when annotator finishes their annotation, and `ExampleAnnotateStartState` is for keeping the time when annotator starts the annotation for each example (we can trigger this endpoint when annotator click on the "Start Annotation" button and when they click the the navigation button to the next example, I think).

### CODE REVIEW

**Review by teddy-f-47 — APPROVED** [review]
Hello, thank you for the great work! I think it is perfect. From the front-end side, we can call the api endpoint at `examples/<int:example_id>/annotate_start_states` to trigger the `perform_create` method, in the annotation page, either in `fetch()` or `create()` (I think it is easier to put it in one of these methods because both the "start annotation" button and navigation button will lead to the same place, let's see XD). So now we will have start-time timestamps for each example. Great! Approved for merging! :)

**Comment by artikandri** [comment]
Thank you for the quick implementation XD  I have tried implementing the API and it works well, but I'm a bit confused. 

From what I see, this API automatically converts the annotation state to `checked` when its called, even though my intention was only to start the timer.. that way, the first item will always be marked as annotated even though I havent started the annotation.

You can check my implementation in this branch: `feature/AffectiveAnnotationProject-viewMode`

Is this behaviour correct (I called the api at the wrong place perhaps)? If it is, how should I implement the API?

**Comment by teddy-f-47** [comment]
> Thank you for the quick implementation XD I have tried implementing the API and it works well, but I'm a bit confused.
> 
> From what I see, this API automatically converts the annotation state to `checked` when its called, even though my intention was only to start the timer.. that way, the first item will always be marked as annotated even though I havent started the annotation.
> 
> You can check my implementation in this branch: `feature/AffectiveAnnotationProject-viewMode`
> 
> Is this behaviour correct (I called the api at the wrong place perhaps)? If it is, how should I implement the API?

Hi Argi, I think it is not the expected behavior of the API, but I think the API's code looks ok (?), I think the API is meant to record the start time of every example's annotation.

I took a look at your branch,  and there is one line in file `frontend/services/application/example/exampleApplicationService.ts`, in `public async annotateStartStates()`:
```
public async annotateStartStates(projectId: string, exampleId: number): Promise<void> {
  await this.repository.confirm(projectId, exampleId)
}
```
I think it should not call `repository.confirm`, and instead it should call `repository.annotateStartStates`....... right? 😅 

edit1: Also btw imo we can call this api not in `toLabeling()` of the "start annotation" button, and instead in the `created()` of the annotation page. But this is not an issue, we can keep it in the "start annotation" button, because the annotation page is already doing quite a lot of api calls XD

edit2: Then again, I think it is better to put in in `created()`, because if we put it in "start annotation" button then we also need to put it in the navigation buttons of the annotation page (note that the api endpoint is designed to record the start time of each text, instead of just the start time of one project)

**Comment by artikandri** [comment]
> > Thank you for the quick implementation XD I have tried implementing the API and it works well, but I'm a bit confused.
> > From what I see, this API automatically converts the annotation state to `checked` when its called, even though my intention was only to start the timer.. that way, the first item will always be marked as annotated even though I havent started the annotation.
> > You can check my implementation in this branch: `feature/AffectiveAnnotationProject-viewMode`
> > Is this behaviour correct (I called the api at the wrong place perhaps)? If it is, how should I implement the API?
> 
> Hi Argi, I think it is not the expected behavior of the API, but I think the API's code looks ok (?), I think the API is meant to record the start time of every example's annotation.
> 
> I took a look at your branch, and there is one line in file `frontend/services/application/example/exampleApplicationService.ts`, in `public async annotateStartStates()`:
> 
> ```
> public async annotateStartStates(projectId: string, exampleId: number): Promise<void> {
>   await this.repository.confirm(projectId, exampleId)
> }
> ```
> 
> I think it should not call repository.confirm, and instead it should call repository.annotateStartStates....... right? sweat_smile
> 
> edit: Also btw imo we can call this api not in `toLabeling()` of the "start annotation" button, and instead in the `created()` of the annotation page. But this is not an issue, we can keep it in the "start annotation" button, because the annotation page is already doing quite a lot of api calls XD

Oh sorry, my mistake XD  Yeah, I called the wrong API. So everything is OK then XD 

As for your comment, no; from what I understand, the api call should start when we start annotating... if it's called on `created`  then it will always call the api  on reload :)   And I'm not sure if that's what's requested

**Review by artikandri — APPROVED** [review]

**Comment by teddy-f-47** [comment]
> > > Thank you for the quick implementation XD I have tried implementing the API and it works well, but I'm a bit confused.
> > > From what I see, this API automatically converts the annotation state to `checked` when its called, even though my intention was only to start the timer.. that way, the first item will always be marked as annotated even though I havent started the annotation.
> > > You can check my implementation in this branch: `feature/AffectiveAnnotationProject-viewMode`
> > > Is this behaviour correct (I called the api at the wrong place perhaps)? If it is, how should I implement the API?
> > 
> > 
> > Hi Argi, I think it is not the expected behavior of the API, but I think the API's code looks ok (?), I think the API is meant to record the start time of every example's annotation.
> > I took a look at your branch, and there is one line in file `frontend/services/application/example/exampleApplicationService.ts`, in `public async annotateStartStates()`:
> > ```
> > public async annotateStartStates(projectId: string, exampleId: number): Promise<void> {
> >   await this.repository.confirm(projectId, exampleId)
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I think it should not call repository.confirm, and instead it should call repository.annotateStartStates....... right? sweat_smile
> > edit: Also btw imo we can call this api not in `toLabeling()` of the "start annotation" button, and instead in the `created()` of the annotation page. But this is not an issue, we can keep it in the "start annotation" button, because the annotation page is already doing quite a lot of api calls XD
> 
> Oh sorry, my mistake XD Yeah, I called the wrong API. So everything is OK then XD
> 
> As for your comment, no; from what I understand, the api call should start when we start annotating... if it's called on `created` then it will always call the api on reload :) And I'm not sure if that's what's requested

Oh, you are right. I forgot about the reloads XD Then there is no other way -- we need to put the code that calls the api in the "start annotation" button and the navigations buttons XD

**Comment by haanh764** [comment]
Haha sorry I missed the conversation here XD So I will merge it now XD thank you XD

**Pull request merged**
