### PR TITLE
feat: Scale labels auto-import, annotation break after finishing a project

### PR DESCRIPTION
**Pull request by teddy-f-47**
This PR aims to solve 2 things: (1) adding an automatic import of scale labels for affective annotation project, (2) creating an annotation break mechanism after finishing a project.

The annotation break is implemented inside the annotatin page, in method `async updateProgress()`. This method is normally used for updating the annotation progress bar. The progress bar increases each time a text has been marked as done / confirmed, until eventually it reaches 100%. I added some code to check if there is no more text to annotate, and if yes then set the `restingEndTime` (calculated as current datetime plus **5 minutes**) and redirect to project list page, on which a message will be shown.

Notably, the resting period is currently hard-coded as 5 minutes from the moment the user marked the last text as done. Later we can add an option to variably set how many minutes to rest, but for now I think 5 minutes is ok.

# Scale labels auto-import
What's changed:
 - frontend/pages/projects/create.vue : Add the automatic import of scale labels file based on the mode after project creation

# Annotation break after finishing a project
What's changed:
 - frontend/package.json : Added `vuex-persistedstate` dependency, which is needed to prevent losing stored data upon refresh.
 - frontend/yarn.lock : Changed due to adding `vuex-persistedstate`.
 - frontend/nuxt.config.js : Registered the new plugin `persistedState.client.js`.
 - frontend/store/auth.js : Added `restingEndTime` to the state, which is for storing the end time of the resting period as a datetime string.
 - frontend/pages/projects/index.vue : Added a check if current time is greater than `restingEndTime`. If not, then show `RestingPeriodModal`.
 - frontend/pages/projects/_id/affective-annotation/index.vue : Modified method `async updateProgress()`, it now checks if all texts have been confirmed, and if yes then it will set the resting period and redirect the user to the project list page. Also, added a similar mechanism of checking `restingEndTime` in `async created()` to prevent user jumping straight into the annotation page by typing the url.
 - frontend/i18n/* : Add translations for the message in the resting modal

What's new:
 - frontend/plugins/persistedState.client.js : A plugin for making all data in vuex store persistent.
 - frontend/components/utils/RestingPeriodModal.vue : A modal that is shown full-screen when user should be in resting period.

### CODE REVIEW

**Comment by haanh764** [comment]
Hello, thank you for your great idea of break after finishing 1 project! I am checking but unfortunately, I am having 1 issue when compile the frontend
```
Failed to compile with 1 errors               friendly-errors 11:37:55

This dependency was not found:                        friendly-errors 11:37:55
                                                      friendly-errors 11:37:55
* vuex-persistedstate in ./plugins/persistedState.client.js
```
Can you check it please?

**Comment by teddy-f-47** [comment]
> Hello, thank you for your great idea of break after finishing 1 project! I am checking but unfortunately, I am having 1 issue when compile the frontend
> 
> ```
> Failed to compile with 1 errors               friendly-errors 11:37:55
> 
> This dependency was not found:                        friendly-errors 11:37:55
>                                                       friendly-errors 11:37:55
> * vuex-persistedstate in ./plugins/persistedState.client.js
> ```
> 
> Can you check it please?

Ah yes, you need to run `yarn install` before running `yarn dev`, due to the added dependency. There was also another error because the yarn lock file somehow changed one of the urls from https:// to git:// but I have fixed it too in a recent commit. 😅

**Comment by teddy-f-47** [comment]
Hi all, I recently added the translations for the resting message. I also added a logout button in the full-screen modal, because I think there can be a case when a user has finished their work hour for the day and want to simply logout. XD

Short demo (notice that before clicking the "confirm as done" button, the progress is already 94% so it was the last text in the project):
Untitled

**Review by haanh764 — APPROVED** [review]
Thank you again for great work! I have tested and everything works fine now! Approved XD

**Comment by artikandri** [comment]
Thank you for the great idea XD Unfortunately being a curious person I am, I tried going to the annotation page by URL and it appears that I can still annotate and not being redirected to the modal XD    Or does this case just happen in my machine? 

Edit: forgot to comment about the code
As for the code, good job! My comment is just to group the code about showing the modal. As for the modal, the good approach would be to use the `v-model` to show it instead of v-if, but this approach works so I think it's fine.

**Comment by teddy-f-47** [comment]
> Thank you for the great idea XD Unfortunately being a curious person I am, I tried going to the annotation page by URL and it appears that I can still annotate and not being redirected to the modal XD Or does this case just happen in my machine?

oh really 0_0 i thought it should work because the code is checked in created(), and i think i have tested it too yesterday..... but anything can go wrong with doccano so i will check it once more XD XD

**Comment by teddy-f-47** [comment]
> Thank you for the great idea XD Unfortunately being a curious person I am, I tried going to the annotation page by URL and it appears that I can still annotate and not being redirected to the modal XD Or does this case just happen in my machine?
> 
> Edit: forgot to comment about the code As for the code, good job! My comment is just to group the code about showing the modal. As for the modal, the good approach would be to use the `v-model` to show it instead of v-if, but this approach works so I think it's fine.

oh okay, I see the problem. the user can still go to the annotation page by entering the url manually.... here the annotation inputs are not displayed, so they can't actually continue annotating, but still ideally the modal should be shown. I will try to fix it.

**Comment by teddy-f-47** [comment]
> Thank you for the great idea XD Unfortunately being a curious person I am, I tried going to the annotation page by URL and it appears that I can still annotate and not being redirected to the modal XD Or does this case just happen in my machine?
> 
> Edit: forgot to comment about the code As for the code, good job! My comment is just to group the code about showing the modal. As for the modal, the good approach would be to use the `v-model` to show it instead of v-if, but this approach works so I think it's fine.

Hi, I have fixed the issue. The problem was the modal was placed outside `layout-text` so apparently it was rendered 'below' the annotation page. Now I think it should work. XD Would you please check again?

About the grouping, I have refactored the code a bit and put the code for showing the modal in a method. And for the v-if, because I think the modal should only be rendered only once per page load, I think it ok (?) because I was thinking v-model and v-show are for components that need to be toggled frequently (?)

**Review by artikandri — APPROVED** [review]
Hello, I have tested the code again and it works well, thank you for the good work! Approved XD

**Pull request merged**
