### PR TITLE
Feat: FE - Questionnaire (Base)

### PR DESCRIPTION
**Pull request by artikandri**
Updated Description

This PR provides the questionnaire UI. Important to note, each annotator is expected to use the same device and browser all the time during the pilot study. This is because their questionnaire progress/history is saved in the browser's local storage, so if an annotator uses a different device/browser then they will need to restart the questionnaires from zero. In addition, it is recommended for each annotator to have their own device, although we have implemented a mechanism that saves questionnaire histories of different users in case multiple users share the same device.

Screenshots:

What's changed:
 1. frontend/plugins/services.ts : Add the newly added questionnaire service
 2. frontend/store/user.js : Add new additional states to store info related to questionnaire
 3. frontend/components/auth/FormLogin.vue : Store loginTime, isFirstLogin, init questionnaire
 4. frontend/components/example/ArticleList.vue : Adjust code style
 5. frontend/components/project/ProjectList.vue : Adjust code style
 6. frontend/components/tasks/affectiveAnnotation/humor/HumorInput.vue : Adjust code style
 7. frontend/components/tasks/affectiveAnnotation/inputs/TextfieldModal.vue : Adjust code style
 8. frontend/layouts/project.vue : Add `check-questionnaire` middleware
 9. frontend/layouts/workspace.vue : Add `check-questionnaire` middleware
 10. frontend/pages/projects/_id/affective-annotation/index.vue : Handle questionnaire timing and track number of annotations made today
 11. frontend/pages/projects/_id/dataset/index.vue : Minor code refactor
 12. frontend/pages/projects/index.vue : Add `check-questionnaire` middleware
 13. frontend/i18n/de/index.js : Add messages translation
 14. frontend/i18n/de/rules.js : Add messages translation
 15. frontend/i18n/en/index.js : Add messages translation
 16. frontend/i18n/en/rules.js : Add messages translation
 17. frontend/i18n/fr/index.js : Add messages translation
 18. frontend/i18n/fr/rules.js : Add messages translation
 19. frontend/i18n/pl/index.js : Add messages translation
 20. frontend/i18n/pl/rules.js : Add messages translation
 21. frontend/i18n/zh/index.js : Add messages translation
 22. frontend/i18n/zh/rules.js : Add messages translation

What's new:
 23. frontend/domain/models/questionnaire/questionnaire.ts : Add the Typescript classes related to the questionnaire
 24. frontend/domain/models/questionnaire/questionnaireRepository.ts : Add the Typescript classes related to the questionnaire
 25. frontend/repositories/questionnaire/apiQuestionnaireRepository.ts : Add api endpoints related to questionnaire
 26. frontend/services/application/example/exampleQuestionnaire.ts : Add the services and Typescript classes related to the questionnaire
 27. frontend/services/application/questionnaire/questionnaireApplicationService.ts : Add the services and Typescript classes related to the questionnaire
 28. frontend/services/application/questionnaire/questionnaireData.ts : Add the services and Typescript classes related to the questionnaire
 29. frontend/utils/questionnaires.js : Add new utils file to store functions handle the questionnaires, as well as storing the original questionnaire structure
 30. frontend/middleware/check-questionnaire.js : Add new middleware to show the questionnaire and prevent redirects
 31. frontend/components/questionnaires/GreetingCard.vue : Add greeting message that appears before each questionnarie
 32. frontend/components/questionnaires/QuestionnaireForm.vue : Add form component for questionnaire
 33. frontend/components/questionnaires/form/DynamicSelectInput.vue : Add input component to be used inside a questionnaire form
 34. frontend/components/questionnaires/form/RadioInput.vue : Add input component to be used inside a questionnaire form
 35. frontend/components/questionnaires/form/ScaleInput.vue : Add input component to be used inside a questionnaire form
 36. frontend/components/questionnaires/form/SelectInput.vue : Add input component to be used inside a questionnaire form
 37. frontend/components/questionnaires/form/SliderInput.vue : Add input component to be used inside a questionnaire form
 38. frontend/components/questionnaires/form/TextInput.vue : Add input component to be used inside a questionnaire form
 39. frontend/layouts/questionnaire.vue : Add new layouts to handle the questionnaire
 40. frontend/layouts/questionnaires.vue : Add new layouts to handle the questionnaire
 41. frontend/pages/questionnaires/index.vue : Add new page for showing greeting message
 42. frontend/pages/questionnaires/codziennie_w_trakcie/index.vue : Add new page for daily questionnaire
 43. frontend/pages/questionnaires/codziennie_w_trakcie/js/questionnaires.js : Add data mapping for daily questionnaire
 44. frontend/pages/questionnaires/na_koniec/index.vue : Add new page for questionnaire at the end
 45. frontend/pages/questionnaires/na_koniec/js/questionnaires.js : Add data mapping for questionnaire at the end
 46. frontend/pages/questionnaires/po_1_tygodniu_i_na_koncu/index.vue : Add new page for questionnaire after 1 week and at the end
 47. frontend/pages/questionnaires/po_1_tygodniu_i_na_koncu/js/questionnaires.js : Add data mapping for questionnaire after 1 week and at the end
 48. frontend/pages/questionnaires/po_2_tygodniach/index.vue : Add new page for questionnaire after 2 weeks
 49. frontend/pages/questionnaires/po_2_tygodniach/js/questionnaires.js : Add data mapping for questionnaire after 2 weeks
 50. frontend/pages/questionnaires/przed_badaniem/index.vue : Add new page for questionnaire before start research
 51. frontend/pages/questionnaires/przed_badaniem/js/questionnaires.js : Add data mapping for questionnaire before start research
 52. frontend/pages/questionnaires/przed_i_po_badaniu/index.vue : Add new page for questionnaire before and after research
 53. frontend/pages/questionnaires/przed_i_po_badaniu/js/questionnaires.js : Add data mapping for questionnaire before and after research
 54. frontend/i18n/de/questionnaires/main.js : New message translations for questionnaire
 55. frontend/i18n/en/questionnaires/main.js : New message translations for questionnaire
 56. frontend/i18n/fr/questionnaires/main.js : New message translations for questionnaire
 57. frontend/i18n/pl/questionnaires/main.js : New message translations for questionnaire
 58. frontend/i18n/zh/questionnaires/main.js : New message translations for questionnaire

### CODE REVIEW

**Comment by teddy-f-47** [comment]
Hello, I have taken a look at the code and app in this branch. I just want to point out that, as far as I remember, this part is not supposed to be shown in doccano:
Capture

I think Kamil said that the source is just written in the doc for "us" i.e. the researchers to be aware of the source of the questionnaire, but it does not need to be shown to the annotators. Unless I misunderstood. XD Maybe @haanh764 can confirm this?

**Comment by haanh764** [comment]
> Hello, I have taken a look at the code and app in this branch. I just want to point out that, as far as I remember, this part is not supposed to be shown in doccano: Capture
> 
> I think Kamil said that the source is just written in the doc for "us" i.e. the researchers to be aware of the source of the questionnaire, but it does not need to be shown to the annotators. Unless I misunderstood. XD Maybe @haanh764 can confirm this?

Yes, I confirm that this part is just for reference, it wont be appeared in the UI :sweat_smile:

**Comment by teddy-f-47** [comment]
In addition, I just tried using the API. I have fixed the API endpoint URL to `answers` in my local branch and now it works, but there is a weird behavior here:
capt2

The first time I answer any question, the saved answer is always "0" no matter what I selected. I think the problem is in the FE code, because when I check the sent payload, the `answer_text` is set to "0". I am aware that the branch is still buggy, just want to point out in case any of us encounter it too XD

**Comment by haanh764** [comment]
Hello, so I am aware about the bugs in the branch also then for now it's oke. Only a notice about this `Szanowny Uczestniku, Szanowna Uczestniczko, Poniżej znajduje się seria kwestionariuszy z pytaniami zamkniętymi. Prosimy o szczere odpowiedzi na każde pytanie....`, it will be appeared before each questionnaire, not before each questionnaire type (just noted for later work XD)

**Comment by artikandri** [comment]
My goodness, this PR is only halfway so of course there's bugs everywhere XD  it's not even done lol. But okay, thank you, and I will fix the part about the footer also

**Review by teddy-f-47 — APPROVED** [review]
After PR #64 is merged into this branch, I think this PR is ready to be merged to the main AffectiveAnnotationProject branch. So I give my approval now. :) Tomorrow morning I will update the PR description (just for documentation purpose).

**Review by haanh764 — APPROVED** [review]
Hello, I think everything works fine so I give my approval now also :smile: Thank you for great work!

**Pull request merged**
