### PR TITLE
fix: Make scale legend in questionnaire sticky

### PR DESCRIPTION
**Pull request by teddy-f-47**
This PR fixes the scale legend on the questionnaire page to be sticky properly.

Screenshot:
fixStickyLegend

What's changed:
 - frontend/components/questionnaires/QuestionnaireForm.vue: Implement css position sticky to scale legend and adjust all of its parents
 - frontend/pages/questionnaires/codziennie_w_trakcie/index.vue: Add position relative and overflow visible to make sticky work
 - frontend/pages/questionnaires/na_koniec/index.vue: Add position relative and overflow visible to make sticky work
 - frontend/pages/questionnaires/po_1_tygodniu_i_na_koncu/index.vue: Add position relative and overflow visible to make sticky work
 - frontend/pages/questionnaires/po_2_tygodniach/index.vue: Add position relative and overflow visible to make sticky work
 - frontend/pages/questionnaires/przed_badaniem/index.vue: Add position relative and overflow visible to make sticky work
 - frontend/pages/questionnaires/przed_i_po_badaniu/index.vue: Add position relative and overflow visible to make sticky work

### CODE REVIEW

**Comment by artikandri** [comment]
Hello, thank you for the good work. I have checked the code and the styling and overall it looks fine, but I got a comment about the segment legend, which I have mentioned earlier in a separated discussion. From what I see, the legend now is showing only the legend from the first segment, which may not be ideal if we have > 1 segments and each segment has different legend. I understand that it's hard to put a dynamic legend based on its scroll position, and it might not be urgent, but I will add it here as a note. I will give my approval after testing it later.

**Comment by teddy-f-47** [comment]
> Hello, thank you for the good work. I have checked the code and the styling and overall it looks fine, but I got a comment about the segment legend, which I have mentioned earlier in a separated discussion. From what I see, the legend now is showing only the legend from the first segment, which may not be ideal if we have > 1 segments and each segment has different legend. I understand that it's hard to put a dynamic legend based on its scroll position, and it might not be urgent, but I will add it here as a note. I will give my approval after testing it later.

Thank you for the feedback! Yes, currently the scale legend only show description from the first segment. Since in our earlier discussion we have agreed that right now there is no real need to handle the case with a questionnaire consisting of multiple segments with different scale descriptions (because right now every questionnaire has the same scale descriptions for all of its segments), I decided to keep it as it is for now, as the other tasks were more urgent and required more effort. 😅

**Review by haanh764 — APPROVED** [review]
Hello, thank you for your nice work! I've checked and it works oke. So approved for merging!

**Comment by artikandri** [comment]
> > Hello, thank you for the good work. I have checked the code and the styling and overall it looks fine, but I got a comment about the segment legend, which I have mentioned earlier in a separated discussion. From what I see, the legend now is showing only the legend from the first segment, which may not be ideal if we have > 1 segments and each segment has different legend. I understand that it's hard to put a dynamic legend based on its scroll position, and it might not be urgent, but I will add it here as a note. I will give my approval after testing it later.
> 
> Thank you for the feedback! Yes, currently the scale legend only show description from the first segment. Since in our earlier discussion we have agreed that right now there is no real need to handle the case with a questionnaire consisting of multiple segments with different scale descriptions (because right now every questionnaire has the same scale descriptions for all of its segments), I decided to keep it as it is for now, as the other tasks were more urgent and required more effort. sweat_smile

Yes, I understand and I remember that, that's why I said it is just a note XD  Because it's better to have it documented here instead. I have tested it and it works well, thank you! Approved.

**Review by artikandri — APPROVED** [review]

**Review by XeonBloomfield — APPROVED** [review]

**Pull request merged**
