### PR TITLE
Feature/affective annotation project project filter

### PR DESCRIPTION
**Pull request by artikandri**
Feature added with this PR: 
- Projects on projects page will be automatically filtered based on their completion status when we logged in as user
- `projects/progress` api implementation (https://github.com/CLARIN-PL/doccano/pull/46) 

What's changed: 
- `frontend/components/project/ProjectList.vue`: implemented `footerProps` and `showSelect` props from user perspective
- `frontend/domain/models/metrics/metrics.ts`: new TS Interface
- `frontend/domain/models/metrics/metricsRepository.ts`: `fetchMyProgresses` api implementation
- `frontend/repositories/metrics/apiMetricsRepository.ts`: `fetchMyProgresses` api implementation
- `frontend/services/application/metrics/metricsApplicationService.ts`: `fetchMyProgresses` api implementation
- `frontend/services/application/project/projectData.ts`: `isCompleted` property 
- `frontend/pages/projects/index.vue`: projects filter implementation
- `frontend/i18n/*/generic.js`: translation
- `frontend/nuxt.config.js`: router middleware

What's new: 
- `frontend/middleware/check-project.js`: middleware to check the project from url, redirect when project is completed 

Notable: 
I limited the datatable to only request 50,100 items per page instead of 10,50,100 per page when we logged in as user, because of the filter :")   After the filter, the project datatable will display different number of items than requested. 
Suppose we have 16 items and requested 10 items -> after filtering, only 2 left of 10 -> we only display 2 items of 10; but the datatable knows that we requested 10 items and that we got 10 items, so the label in the datatable will say `1-10 of 10` instead of `1-2 of 2` XD   We can set the count with items.length so that the text become `1-2 of 2`, but then we will have another problem; we wont be able to go to the next page and the next 6 items wont be accessible  XD  so this bug is left intentionally for now and for the workaround, I set the items to 50 XD  That way the bug wont be so visible lol (please comment on this approach) 
 
Screenshots: 
As admin: 
image

As user: 
image

### CODE REVIEW

**Review by haanh764 — COMMENTED** [review]
Hello thank you for you nice work XD I have tested and the project filter works well and the api implementation looks fine also.
About the issue with the item per page counting, I got your point but I understand from your example that if we have 16 projects, and request 10 projects per page (so it will be `1-10 of 16` in the first page). After filtering, the first page has only 2 projects left, right(?) So I understand that it will be `1-2 of 16` or `1-10 of 16` not `1-10 of 10` as what I see currently in doccano, right (?)
And can we re-count the total number of project left which is 8 now (then it will be `1-2 of 8` not `1-2 of 2`) (?) and possibly to show all of them in the first page (something like push the items in the 2nd page to the first page) (?) 
And currently, by setting the request to 50, it's just for distracting the users from noticing that counting per page, right :smile: Because I have 25 projects here, 2 of them have done but the counting is still `1-25 of 25` 
https://user-images.githubusercontent.com/17596118/199993067-95e32380-06c1-45b0-94bf-673656b9b1c1.png

These are just questions because I want to confirm that I understand you correctly XD

**Comment by artikandri** [comment]
> And currently, by setting the request to 50, it's just for distracting the users from noticing that counting per page, right 

Yes exactly XD    and I doubt one user can have > 50 projects so- 

> And can we re-count the total number of project left which is 8 now (then it will be 1-2 of 8 not 1-2 of 2) (?) and possibly to show all of them in the first page (something like push the items in the 2nd page to the first page) (?)

Sadly no TT^TT the number is decided by datatable by giving the `count` from the `projects` api, and this number is crucial because it will tell datatable how much data we actually have TT^TT   and we cant give our filtered number for it 
Pushing the items from the 2nd page will also not be possible, because with the datatable, the api request query is handled by the datatable (offset, number of items, and so on), and it will mess up the system

**Comment by teddy-f-47** [comment]
Hi! Thank you for the great work. I have seen the code and also tested the app, and I think in general it is working fine.

About the issue with displaying the number of projects after the projects are filtered, I agree, I think we cannot change the numbers written at the bottom of the datatable for reasons you have mentioned. But setting the itemsPerPage to 50 is like just covering the issue, because when the total projects number assigned to the user gets greater than 50 then the problem will be visible again XD

My suggestion is that, maybe we can show somewhere else the number of the filtered (uncomplete) projects? Maybe something like this (just for the sake of example I put back the 10 items per page option, to simulate the situation that may happen later when the user has more projects than 50):
Capture2

In the example, if the user is seeing the `1-10 of 11` alone, they may get confused (even though we have written on the top that completed projects can no longer be viewed), as in the list there are only 7 projects listed and the next project(s) are in the next page. Imo adding such information like the red text I wrote in the screenshot can provide some extra clarity. XD What do you think?

**Comment by artikandri** [comment]
> Hi! Thank you for the great work. I have seen the code and also tested the app, and I think in general it is working fine.
> 
> About the issue with displaying the number of projects after the projects are filtered, I agree, I think we cannot change the numbers written at the bottom of the datatable for reasons you have mentioned. But setting the itemsPerPage to 50 is like just covering the issue, because when the total projects number assigned to the user gets greater than 50 then the problem will be visible again XD
> 
> My suggestion is that, maybe we can show somewhere else the number of the filtered (uncomplete) projects? Maybe something like this (just for the sake of example I put back the 10 items per page option, to simulate the situation that may happen later when the user has more projects than 50): Capture2
> 
> In the example, if the user is seeing the `1-10 of 11` alone, they may get confused (even though we have written on the top that completed projects can no longer be viewed), as in the list there are only 7 projects listed and the next project(s) are in the next page. Imo adding such information like the red text I wrote in the screenshot can provide some extra clarity. XD What do you think?

Hello, thank you for the great idea XD Didn't think of that before, I was too focused on fixing the bugs XD      Okay, I will add it

**Comment by artikandri** [comment]
Hello everyone, I have implemented above suggestion, what do you think XD  

image

**Review by haanh764 — APPROVED** [review]
Hello, I think it's a clearer way to handle that XD I've tested and I think it's oke now, so approved XD
Btw, when I compiled the frontend, there's an error as below, it does not affect the function I think, but please check it :sweat_smile: 
Screenshot from 2022-11-07 10-33-59

**Comment by artikandri** [comment]
> Hello, I think it's a clearer way to handle that XD I've tested and I think it's oke now, so approved XD Btw, when I compiled the frontend, there's an error as below, it does not affect the function I think, but please check it sweat_smile Screenshot from 2022-11-07 10-33-59

Thank you for pointing it out XD I forgot to check the `yarn` tab as per usual. Fixed!

**Review by teddy-f-47 — APPROVED** [review]
Thank you for the great work! Approved for merging. :) A very, very minor comment is just about the color of the text, it doesn't have to be red (my screenshot was just an example, I added it in paint XD). But imo it is fine, so if you also think the color is fine (i.e. it is matches the rest of the app, not too contrasting), then let it be. XD

**Comment by artikandri** [comment]
> Thank you for the great work! Approved for merging. :) A very, very minor comment is just about the color of the text, it doesn't have to be red (my screenshot was just an example, I added it in paint XD). But imo it is fine, so if you also think the color is fine (i.e. it is matches the rest of the app, not too contrasting), then let it be. XD

Lol okiee XD I will think of it and fix it later when I worked on this again (or probably if I fixed future PR), but for now, I will let it be XD   Thank you!

**Pull request merged**
