### PR TITLE
Feat: FE- AffectiveAnnotationProject - Single annotation view 

### PR DESCRIPTION
**Pull request by artikandri**
## Dataset page
What's changed: 
- `frontend/components/example/ArticleList.vue`: hide checkbox when logged in as non-admin, hide annotation button on `showAnnotationButton` prop value, add `isConfirmed` status column to the table 
- `frontend/components/utils/ActionMenu.vue`: added `buttonColor` prop so that we can adjust the button color; previously it defaults on `primary` (blue)
- `frontend/domain/models/example/exampleRepository.ts`: added the api to create new state to the repository
- `frontend/i18n/*/projects/dataset.js`: new translations for the dataset page
- `frontend/pages/projects/_id/dataset/index.vue`: added `start annotation` button above the table, adjusted the table, added `annotation status` filter to filter the table, added a function to call the api when clicking the `start annotation` button
- `frontend/services/application/example/exampleData.ts`: added `isConfirmed` status to the Typescript data model
- `frontend/repositories/example/apiDocumentRepository.ts`: loaded `annotateStartStates` api to the repository
- `frontend/services/application/example/exampleApplicationService.ts`: loaded `annotateStartStates` api to the services

Screenshots: 
Admin view: 
image

User view: 
image
 
## Annotation page
What's changed: 
- `frontend/components/tasks/*/*/*.vue`: added a `readOnly` prop to prevent user from editing the annotations once they have confirmed the annotations
- `frontend/components/tasks/affectiveAnnotation/humor/HumorInput.vue`: added a `readOnly` prop to prevent user from editing the annotations once they have confirmed the annotations, added scaleTypes check to make sure the right scales were imported
- `frontend/components/tasks/affectiveAnnotation/offensive/OffensiveInput.vue`: added a `readOnly` prop to prevent user from editing the annotations once they have confirmed the annotations, added scaleTypes check to make sure the right scales were imported
- `frontend/components/tasks/toolbar/ToolbarLaptop.vue`: added `buttonOptions` prop to handle visibility/disability/hidden status of the buttons, worked around the `button-pagination` $emit events to execute callbacks. Tested on other project types. 
- `frontend/components/tasks/toolbar/buttons/ButtonClear.vue`: added `disabled` prop
- `frontend/components/tasks/toolbar/buttons/ButtonReview.vue`: added `disabled`, `showText`, and `text` props. They default as false so it shouldn't affect other views 
- `frontend/components/tasks/toolbar/buttons/ButtonPagination.vue`: added title on pagination button hover, adjusted button disabled status and `@click` event, added `callback` on button click
- `frontend/domain/models/project/project.ts`: adjusted Typescript class to handle `is_single_ann_view` value
- `frontend/i18n/*/projects/annotation.js`: new translations for the annotation page
- `frontend/services/application/tasks/affectiveAnnotation/*.ts`: added clear functions to clear the labels when clicking on the `clear` button
- `frontend/pages/projects/_id/affective-annotation/index.vue`: 
--- solve merge conflicts, refactored the code
--- hide buttons and some panels when `isSingleAnnView = true`
--- implemented user and admin perspective; admin can still check and uncheck the annotations as needed, and they can't see the resting modal, but user can. 
--- added a function to call the annotateStartStates api on button pagination click

Screenshots: 
Admin view: 
image

User view: 
image

## Project creation page
- `frontend/components/project/FormCreate.vue`: added radio group buttons to set single ann view value 
- `frontend/pages/projects/create.vue`: adjusted the create.vue to handle newly added `isSingleAnnView` value
- `frontend/services/application/project/projectApplicationService.ts`: handle `isSingleAnnView`
- `frontend/services/application/project/projectData.ts`: handle `isSingleAnnView`

Screenshot: 
image

## Other
- `frontend/pages/projects/index.vue`: added `isStaff` check so that showRestingMessage modal won't be showing when we logged in as `admin`

### CODE REVIEW

**Review by teddy-f-47 — COMMENTED** [review]
Hello, thank you very much for your hard work! I have tested the app and mostly almost everything is fine. There are a few comments though:

0. I think you should also add the api endpoint `annotateStartStates` calling into the "start annotation" button in `frontend/components/layout/TheSideBar.vue`.
1. There seems to be a bug in the start annotation time logging, but I think the issue is in the BE. So, when I click "start annotation", annotate and confirm current text (text A), and go to the next text (text B), now the DB has my start time on text B. However, if now I go back to previous text (text A) and come back again to text B, the record of my start time on text B in DB is somehow erased. So, if I now annotate and confirm text B, and go to the next text (text C), the DB will not have my start time on text B. [Expected behavior on BE: if the text indicated by the example_id hasn't been confirmed, the start time of that text should be updated to the current datetime (and if it has been confirmed, the start time should not change -- but this case has been safe-guarded in FE to some degree by not calling the api endpoint if the text is confirmed).] @haanh764 what do you think?
2. In single-text annotation view, I think everything is fine. But I see that in the whole-article annotation view, not everything is implemented similarly, for example user can still change annotations after confirming, jump to any text, in whole-article view. Is this intended?
3. There is now a bug in Others mode, but I will help investigate it myself after this PR is merged. Most probably it is caused by the "nie wiem" checkbox conflicting with the disabling mechanism when confirmed.

**Comment by artikandri** [comment]
> Hello, thank you very much for your hard work! I have tested the app and mostly almost everything is fine. There are a few comments though:
> 
> 0. I think you should also add the api endpoint `annotateStartStates` calling into the "start annotation" button in `frontend/components/layout/TheSideBar.vue`.
> 1. There seems to be a bug in the start annotation time logging, but I think the issue is in the BE. So, when I click "start annotation", annotate and confirm current text (text A), and go to the next text (text B), now the DB has my start time on text B. However, if now I go back to previous text (text A) and come back again to text B, the record of my start time on text B in DB is somehow erased. So, if I now annotate and confirm text B, and go to the next text (text C), the DB will not have my start time on text B. [Expected behavior on BE: if the text indicated by the example_id hasn't been confirmed, the start time of that text should be updated to the current datetime (and if it has been confirmed, the start time should not change -- but this case has been safe-guarded in FE to some degree by not calling the api endpoint if the text is confirmed).] @haanh764 what do you think?
> 2. In single-text annotation view, I think everything is fine. But I see that in the whole-article annotation view, not everything is implemented similarly, for example user can still change annotations after confirming, jump to any text, in whole-article view. Is this intended?
> 3. There is now a bug in Others mode, but I will help investigate it myself after this PR is merged. Most probably it is caused by the "nie wiem" checkbox conflicting with the disabling mechanism when confirmed.

1. Ah sorry, it's a bit impossible. The item in that function is not returned to the frontend;  rather than adding the button, I was thinking of hiding the button completely, but I removed the code to hide the button earlier because I thought it was not requested XD  I probably can work on it but it will require a bit of adjustment in the service api
2. As you have seen, I have added the `isConfirmed` check for that XD   But I didnt check DBeaver the whole time so I'm not sure. 
3. It's intended, because I only handled the request for `single ann view = true` and let the article view retains its original behavior XD  I can remove the `singleAnnView` check tho 
4. Ah I'm sorry, I didn't check that; I was checking everything to make sure it's disabled but I didn't check the functionality.

**Comment by haanh764** [comment]
> Hello, thank you very much for your hard work! I have tested the app and mostly almost everything is fine. There are a few comments though:
> 
> 0. I think you should also add the api endpoint `annotateStartStates` calling into the "start annotation" button in `frontend/components/layout/TheSideBar.vue`.
> 1. There seems to be a bug in the start annotation time logging, but I think the issue is in the BE. So, when I click "start annotation", annotate and confirm current text (text A), and go to the next text (text B), now the DB has my start time on text B. However, if now I go back to previous text (text A) and come back again to text B, the record of my start time on text B in DB is somehow erased. So, if I now annotate and confirm text B, and go to the next text (text C), the DB will not have my start time on text B. [Expected behavior on BE: if the text indicated by the example_id hasn't been confirmed, the start time of that text should be updated to the current datetime (and if it has been confirmed, the start time should not change -- but this case has been safe-guarded in FE to some degree by not calling the api endpoint if the text is confirmed).] @haanh764 what do you think?
> 2. In single-text annotation view, I think everything is fine. But I see that in the whole-article annotation view, not everything is implemented similarly, for example user can still change annotations after confirming, jump to any text, in whole-article view. Is this intended?
> 3. There is now a bug in Others mode, but I will help investigate it myself after this PR is merged. Most probably it is caused by the "nie wiem" checkbox conflicting with the disabling mechanism when confirmed.

Hello, about (1) yeah I see that. The reason is because I thought that we will start annotating 1 example only once, there is no reason (with the current request) we will start twice on a sample, that's why it will query the example id, and if that example already exists in the table, it will be deleted. Ofc I can make it not being deleted and accept the duplication but in that case there will be quite unclear in the future when comparing the duration from starting until finishing annotation of 1 example XD Like you have 2 or even more starting time so which one will be correct XD And I thought that with the current requirement (after confirm, we cant unconfirm - cant edit annotation) -> so there is no reason to go back to the previous confirmed one, right? And this requirement also request the same thing (you can go to the next/previous document but only the "unchecked" one) so I understand that once we confirmed, we can go to the next example only (so only the navigation to the next is clickable, the navigation to the previous is unclickable, right? Because I thought that I told Argi about that but this button still be clickable XD).

Btw, I have a small question on the dataset view, why do we have 2 Start Annotation button :sweat_smile: The one on sidebar when I click, it doesn't call the api for logging timestamp and the button on the right side do. But then it will be quite confuse and the user always can click on the left button instead of the right one (?)

**Comment by artikandri** [comment]
> > Hello, thank you very much for your hard work! I have tested the app and mostly almost everything is fine. There are a few comments though:
> > 
> > 0. I think you should also add the api endpoint `annotateStartStates` calling into the "start annotation" button in `frontend/components/layout/TheSideBar.vue`.
> > 1. There seems to be a bug in the start annotation time logging, but I think the issue is in the BE. So, when I click "start annotation", annotate and confirm current text (text A), and go to the next text (text B), now the DB has my start time on text B. However, if now I go back to previous text (text A) and come back again to text B, the record of my start time on text B in DB is somehow erased. So, if I now annotate and confirm text B, and go to the next text (text C), the DB will not have my start time on text B. [Expected behavior on BE: if the text indicated by the example_id hasn't been confirmed, the start time of that text should be updated to the current datetime (and if it has been confirmed, the start time should not change -- but this case has been safe-guarded in FE to some degree by not calling the api endpoint if the text is confirmed).] @haanh764 what do you think?
> > 2. In single-text annotation view, I think everything is fine. But I see that in the whole-article annotation view, not everything is implemented similarly, for example user can still change annotations after confirming, jump to any text, in whole-article view. Is this intended?
> > 3. There is now a bug in Others mode, but I will help investigate it myself after this PR is merged. Most probably it is caused by the "nie wiem" checkbox conflicting with the disabling mechanism when confirmed.
> 
> Hello, about (1) yeah I see that. The reason is because I thought that we will start annotating 1 example only once, there is no reason (with the current request) we will start twice on a sample, that's why it will query the example id, and if that example already exists in the table, it will be deleted. Ofc I can make it not being deleted and accept the duplication but in that case there will be quite unclear in the future when comparing the duration from starting until finishing annotation of 1 example XD Like you have 2 or even more starting time so which one will be correct XD And I thought that with the current requirement (after confirm, we cant unconfirm - cant edit annotation) -> so there is no reason to go back to the previous confirmed one, right? And this requirement also request the same thing (you can go to the next/previous document but only the "unchecked" one) so I understand that once we confirmed, we can go to the next example only (so only the navigation to the next is clickable, the navigation to the previous is unclickable, right? Because I thought that I told Argi about that but this button still be clickable XD).
> 
> Btw, I have a small question on the dataset view, why do we have 2 Start Annotation button 😅 The one on sidebar when I click, it doesn't call the api for logging timestamp and the button on the right side do. But then it will be quite confuse and the user always can click on the left button instead of the right one (?)

Yeah, I made the prev button clickable but view mode only so I think it shouldn't matter, I already added a check to only  call the api when it's not yet confirmed. I can disable the button but I thought we can still see prev doc, we are just unable to edit it xD   should I disable this?

And as for the sidebar button, as I said, I don't know whether should I hide the button or not, but yeah, I should have removed it, I got confused when writing the PR and reverted the change xD

**Comment by artikandri** [comment]
you can go to the next/previous document but only the "unchecked" one

As for this requirement, it will be a bit hard to achieve this with the current doccano. If I were to limit this, then it will work like my demo yesterday (I overwrote the isChecked value so it will always request the unchecked files), but the problem is, when its reloaded, the api will find the first unchecked doc  xD  and our previously annotated doc will never appear again. The only thing i can do is to disable the button; but then, if we entered it from the url then its useless xD

**Comment by artikandri** [comment]
Hello, I have hidden the sidebar button and disabled the prev/first button when we logged in as non-admin. I also disabled the `start annotation` button when we logged in as non-admin and no longer have unannotated items, so user can still view the annotated items but they have to enter the url for that XD

**Review by teddy-f-47 — APPROVED** [review]
Hello, I have seen the recent code changes and I think it looks fine. Just one more minor remark, I think all those checks based on `this.project.isSingleAnnView` should just be changed to check if the project is of affective annotation type, because we want all these changes to apply to the whole affective annotation project type (there is no point  in differentiating the behavior in whole-article view and single-text view, because we expect them to behave the same with the only difference being the whole-article view showing the left-side article viewer, while the single-text view as it is now). But let it be for now. Approved for merging.

**Comment by artikandri** [comment]
> Hello, I have seen the recent code changes and I think it looks fine. Just one more minor remark, I think all those checks based on `this.project.isSingleAnnView` should just be changed to check if the project is of affective annotation type, because we want all these changes to apply to the whole affective annotation project type (there is no point in differentiating the behavior in whole-article view and single-text view, because we expect them to behave the same with the only difference being the whole-article view showing the left-side article viewer, while the single-text view as it is now). But let it be for now. Approved for merging.

Thank you for the approval! Unfortunately I missed that requirement previously or it was not mentioned earlier, but either way, I will do it on my next PR.

**Review by haanh764 — APPROVED** [review]
Hello, so I have tested and everything works oke for now. Only the point that I told you already XD so you can add it in this pr or next pr, both is oke for me. Approved XD

**Comment by artikandri** [comment]
Hello everyone, I have fixed the bug about skipping to the last page, added additional check for prev button, and disabled the jump button. I will merge it now and future bugs will be handled in future PR, thank you!

**Pull request merged**
