### PR TITLE
fix: Load "none" (-1) value properly when reopening Others annotation page

### PR DESCRIPTION
**Pull request by teddy-f-47**
This PR solves the issue in affective annotation Others mode when marking a "nie wiem" checkbox (in which case, the value is saved as -1 in db), and then user closes the project and reopen it, the checkbox won't be marked. The issue happens with both slider and textlabel inputs in Others mode. However, the issue does not affect the other modes, because only the Others mode contain "nie wiem" checkboxes that are treated as -1 value.

With this fix, "nie wiem" checkboxes should be reloaded correctly for both slider and textlabel inputs.

Notable:
- Because the question "Czego życzę autorowi tego tekstu?" is open question but it can be marked as "none" (-1), there is this "quirk" : when user marks the field as "nie mam życzeń", and then closes the annotation page, and then reopens it, now the checkbox is marked, the textfield is disabled, but the string "-1" is visible inside the textfield. But I think this is rather minor. 😓 I tried to make the text inside the textfield white/transparent when the value is "-1" but I couldn't make it work....

What's changed:
 - frontend/components/tasks/affectiveAnnotation/inputs/Slider.vue : Added v-model to change the checkbox value dynamically
 - frontend/components/tasks/affectiveAnnotation/inputs/TextfieldWithSeq2Seq.vue : Added v-model to change the checkbox value dynamically
 - frontend/pages/projects/_id/affective-annotation/index.vue : Adjustment in the code that handles marking and unmarking checkbox
 
Screenshots:
ss
sss

### CODE REVIEW

**Review by haanh764 — APPROVED** [review]
Thank you for your nice work! I have tested and it works oke! I also see the minor problem with the "-1" in text field, when I added an answer then I changed my mind and click to "Nie mam,,," then in the database my previous answer also becomes "-1". But yeah it's pretty minor, I will see later if I can do something in the backend, if the value is "-1" then it will be removed or something. But now I think it's oke. Approved for merging!

**Comment by teddy-f-47** [comment]
> Thank you for your nice work! I have tested and it works oke! I also see the minor problem with the "-1" in text field, when I added an answer then I changed my mind and click to "Nie mam,,," then in the database my previous answer also becomes "-1". But yeah it's pretty minor, I will see later if I can do something in the backend, if the value is "-1" then it will be removed or something. But now I think it's oke. Approved for merging!

Thank you! But I have a question now.... 😅 I thought that we want to distinguish "not giving any answer at all" (which is like the user hasn't responded at all to the question) and "i don't have any answer" (which is like the user is marking the checkbox)? For the latter case, we set the value as -1. Because of that, I think the backend side doesn't need to change anything....

**Comment by haanh764** [comment]
> > Thank you for your nice work! I have tested and it works oke! I also see the minor problem with the "-1" in text field, when I added an answer then I changed my mind and click to "Nie mam,,," then in the database my previous answer also becomes "-1". But yeah it's pretty minor, I will see later if I can do something in the backend, if the value is "-1" then it will be removed or something. But now I think it's oke. Approved for merging!
> 
> Thank you! But I have a question now.... 😅 I thought that we want to distinguish "not giving any answer at all" (which is like the user hasn't responded at all to the question) and "i don't have any answer" (which is like the user is marking the checkbox)? For the latter case, we set the value as -1. Because of that, I think the backend side doesn't need to change anything....

Ah yeah I forgot that so just let it be XD I thought that they were the same but yeah It could be different XD

**Comment by artikandri** [comment]
Hello, I have tried your code and unfortunately I found a bug in which when I only clicked `I dont have wish` without typing anything, nothing will be saved in the database :"))  I included the video here: 
https://watch.screencastify.com/v/8nFylU7KewQTfa3siGlQ

as for the `-1` bug, it can be solved by adding a check to `:value` property in TextField...seq.vue
```
        <v-text-field
          :disabled="!enableTextfield"
          small
          dense
          readonly
          :value="stringifiedAnswers === '-1' ? '' : stringifiedAnswers"
          :rules="rulesTextfield"
          hide-details="auto"
        />
```

This approach will be neater with the use of computed value or `get` and `set` (check TextfieldModal) but this is fine XD

**Comment by teddy-f-47** [comment]
> Hello, I have tried your code and unfortunately I found a bug in which when I only clicked `I dont have wish` without typing anything, nothing will be saved in the database :")) I included the video here: https://watch.screencastify.com/v/8nFylU7KewQTfa3siGlQ
> 
> as for the `-1` bug, it can be solved by adding a check to `:value` property in TextField...seq.vue
> 
> ```
>         <v-text-field
>           :disabled="!enableTextfield"
>           small
>           dense
>           readonly
>           :value="stringifiedAnswers === '-1' ? '' : stringifiedAnswers"
>           :rules="rulesTextfield"
>           hide-details="auto"
>         />
> ```
> 
> This approach will be neater with the use of computed value or `get` and `set` (check TextfieldModal) but this is fine XD

Oh, I see, thank you very much for catching the bug. I will investigate it -- most probably due to a flawed logic in the `nullifyWishToAuthor` and the `restoreWishToAuthor`..... Also thank you again for the solution with not showing -1, I had a tunnel vision and couldn't see such a simple solution! XD XD

**Comment by teddy-f-47** [comment]
> Hello, I have tried your code and unfortunately I found a bug in which when I only clicked `I dont have wish` without typing anything, nothing will be saved in the database :")) I included the video here: https://watch.screencastify.com/v/8nFylU7KewQTfa3siGlQ
> 
> as for the `-1` bug, it can be solved by adding a check to `:value` property in TextField...seq.vue
> 
> ```
>         <v-text-field
>           :disabled="!enableTextfield"
>           small
>           dense
>           readonly
>           :value="stringifiedAnswers === '-1' ? '' : stringifiedAnswers"
>           :rules="rulesTextfield"
>           hide-details="auto"
>         />
> ```
> 
> This approach will be neater with the use of computed value or `get` and `set` (check TextfieldModal) but this is fine XD

Hello, I have fixed the bug 😅 I apologize for it. I think it should work correctly now. Would you please check again?

**Review by artikandri — APPROVED** [review]
I have tested it again, and it works fine, good job! Considering our current workload, I will not add any more comments, so I will approve it for the time being. But next time, it would be great if you can add a variable called `noWishFlag = -1`, for example, because I think people who are new to this codebase will have a hard time understanding the `-1` flag everywhere XD     Just for consideration.

**Comment by teddy-f-47** [comment]
> I have tested it again, and it works fine, good job! Considering our current workload, I will not add any more comments, so I will approve it for the time being. But next time, it would be great if you can add a variable called `noWishFlag = -1`, for example, because I think people who are new to this codebase will have a hard time understanding the `-1` flag everywhere XD Just for consideration.

You are right 😅 I have refactored it and put the -1 and "-1" values into nullFlag variables. Thank you! I will merge the PR soon. :)

**Pull request merged**
