### PR TITLE
Feat: baseline back-end for Affective Annotation Project

### PR DESCRIPTION
**Pull request by haanh764**
What's changed:
- `backend/projects/models.py`: added class model for new project type `AffectiveAnnotationProject`. For this class, I still keep the property `is_article_project()` because it will use article data also, then we can re-use some code from the ArticleAnnotation without re-implementation. Besides, I added a new property `is_affective_annotation_project()` which could be useful later when we want to define some special functions or something for this project type only XD And the new fields are added including `is_summary_mode`, `is_emotions_mode`, `is_offensive_mode`, `is_humor_mode`, `is_others_mode`, which are for defining the 5 required categories
- `backend/projects/serializers.py`: added serializer for AffectiveAnnotationProject
- `backend/projects/tests/utils.py`, `backend/projects/tests/test_project.py`: added test for project creation for AffectiveAnnotation
- `backend/data_import/datasets.py`: define dataset type for AffectiveAnnotationProject
- `backend/data_import/pipeline/catalog.py`: register data importing options for AffectiveAnnotationProject
- `backend/data_import/pipeline/examples/affective_annotation/example.json`: added example of imported data for AffectiveAnnotationProject
- `backend/data_import/tests/test_tasks.py`: added test tasks for import data for AffectiveAnnotationProject
- `backend/data_export/pipeline/factories.py`, `backend/data_export/pipeline/catalog.py`: added data export for AffectiveAnnotationProject
- `backend/data_export/pipeline/examples/affective_annotation/example.json`: added example of data export for AffectiveAnnotationProject
- `backend/data_export/tests/test_task.py`: added test tasks for export data for AffectiveAnnotationProject

Currently, the table for new project type looks as below:
Screenshot from 2022-09-26 17-05-24

Note: I think the tables related to label types also need to customize also but I will cover them it the next pr XD This pr is for creating the baseline BE of the new project type only XD

### CODE REVIEW

**Review by teddy-f-47 — APPROVED** [review]
I think everything looks fine. Thank you for the nice work! Approved for merging. :)

Also about the label types, it was mentioned that the labels will be hard-coded, to avoid extra complication of importing/exporting labels. So I assume the labels in each metacategory group are fixed and won't change. So on BE side perhaps we need to make a table for each metacategory group (Summary, Emotion, ...). I'm thinking of something like:
```
table Example_Summary (
  id INT PK,
  example_id INT FK,
  annotator_id INT FK,
  tags TEXT, # tagi, słowa kluczowe
  impressions TEXT # wrażenia/emocje/odczucia
)
table Example_Emotions (
  id INT PK,
  example_id INT FK,
  annotator_id INT FK,
  general_positivity INT,
  general_negativity INT,
  love INT, # radość
  ...
)
...
```

Maybe we can just write the field names of the tables in polish language, to avoid confusion in translation. XD And later when exporting, these labels may either be put in the `cats` field of the json or in the `meta` field -- I think we will just need to see later which way is easier XD

Also I think we need to agree on a few things, like:
1) For Summary group, we will treat the data as textfields? So user will input keywords separated by comma, and on FE we can set some validation mechanism to prevent other symbols, but in BE the `tags` ("tagi / słowa kluczowe") will be stored as one long text string and the `impressions` ("wrażenia/emocje/odczucia") will be stored as another one long text string.
2) For any slider, the value should be INT in the range of 0 to 100, I suppose?
3) The checkbox `nie wiem` when checked should be treated as a `NULL` value, to somehow distinguish it from zero and boolean false
4) The other checkboxes are simply treated as true or false

What do you think, @artikandri ? 😅 

Edit:
Maybe we can write the field names of the tables in both polish and english, with the format of `PolishWord_EnglishWord`, for example `radosc_love`, but using only common latin characters so without polish letters. XD I think it will be even more clearer for future development in case we want to make not only polish version but also english or any other language

**Review by artikandri — APPROVED** [review]
Thank you for the superb implementation! I think everything looks good and good to merge, approved! :+1:

**Comment by artikandri** [comment]
> I think everything looks fine. Thank you for the nice work! Approved for merging. :)
> 
> Also about the label types, it was mentioned that the labels will be hard-coded, to avoid extra complication of importing/exporting labels. So I assume the labels in each metacategory group are fixed and won't change. So on BE side perhaps we need to make a table for each metacategory group (Summary, Emotion, ...). I'm thinking of something like:
> 
> ```
> table Example_Summary (
>   id INT PK,
>   example_id INT FK,
>   annotator_id INT FK,
>   tags TEXT, # tagi, słowa kluczowe
>   impressions TEXT # wrażenia/emocje/odczucia
> )
> table Example_Emotions (
>   id INT PK,
>   example_id INT FK,
>   annotator_id INT FK,
>   general_positivity INT,
>   general_negativity INT,
>   love INT, # radość
>   ...
> )
> ...
> ```
> 
> Maybe we can just write the field names of the tables in polish language, to avoid confusion in translation. XD And later when exporting, these labels may either be put in the `cats` field of the json or in the `meta` field -- I think we will just need to see later which way is easier XD
> 
> Also I think we need to agree on a few things, like:
> 
> 1. For Summary group, we will treat the data as textfields? So user will input keywords separated by comma, and on FE we can set some validation mechanism to prevent other symbols, but in BE the `tags` ("tagi / słowa kluczowe") will be stored as one long text string and the `impressions` ("wrażenia/emocje/odczucia") will be stored as another one long text string.
> 2. For any slider, the value should be INT in the range of 0 to 100, I suppose?
> 3. The checkbox `nie wiem` when checked should be treated as a `NULL` value, to somehow distinguish it from zero and boolean false
> 4. The other checkboxes are simply treated as true or false
> 
> What do you think, @artikandri ? sweat_smile
> 
> Edit: Maybe we can write the field names of the tables in both polish and english, with the format of `PolishWord_EnglishWord`, for example `radosc_love`, but using only common latin characters so without polish letters. XD I think it will be even more clearer for future development in case we want to make not only polish version but also english or any other language

1. I wonder about this. This can be a solution; another way is to stringify them as JSON string and frontend can parse that. I think splitting them by their commas will be easier to handle, but ofc, this is for the BE to judge XD    And for the FE too, but I recall that the `summary` is not within my area, or did I remember it wrong? 
2. Yes, I agree with this. 
3. I can't really agree with that. I think its better to store it as true or false; I know the negative statement (nie wiem) may bother you but storing it as null won't be good either since null usually means that the field has no data, if I understood the value correctly :)   
4. Yes, I agree with this.

**Comment by haanh764** [comment]
> 

About the label types, I have some ideas also so we can consider XD
1. About the Summary mode, it will be the textfiled input so I think we can do it like in the Seq2Seq project because it's pretty the same thing. There's a text filed and we can type what ever want and then enter, and then type another thing and enter. You can check table `labels_textlabel`. For eg, here `example_id = 508380` has few label as the text input from textfield: 
Screenshot from 2022-09-27 10-44-34

2. For the other modes which have Labels (likes Radość, szczęście, Zachwyt, podziw, duma, Pozytywne, Negatywne,...etc), we can just use the current table `label_types_categorytype`, because basically the characteristic of them are pretty the same. They are just the categories, and they are already map with example by example_id, and label_id via table `labels_category`. The only thing we need to do is somehow init all of the polish categories in the database on starting the program if there are no those labels. And if the project is in type of Affective Annotation it will use these labels automatically
Screenshot from 2022-09-27 10-54-28

3. The modes using scale, I think we can create a new table for keeping the scale categories, for eg `label_type_scaletype` which keep the scale labels

**Comment by teddy-f-47** [comment]
> > 
> 
> About the label types, I have some ideas also so we can consider XD
> 
> 1. About the Summary mode, it will be the textfiled input so I think we can do it like in the Seq2Seq project because it's pretty the same thing. There's a text filed and we can type what ever want and then enter, and then type another thing and enter. You can check table `labels_textlabel`. For eg, here `example_id = 508380` has few label as the text input from textfield:
>    Screenshot from 2022-09-27 10-44-34
> 2. For the other modes which have Labels (likes Radość, szczęście, Zachwyt, podziw, duma, Pozytywne, Negatywne,...etc), we can just use the current table `label_types_categorytype`, because basically the characteristic of them are pretty the same. They are just the categories, and they are already map with example by example_id, and label_id via table `labels_category`. The only thing we need to do is somehow init all of the polish categories in the database on starting the program if there are no those labels. And if the project is in type of Affective Annotation it will use these labels automatically
>    Screenshot from 2022-09-27 10-54-28
> 3. The modes using scale, I think we can create a new table for keeping the scale categories, for eg `label_type_scaletype` which keep the scale labels

1. I see, for the Summary mode, it is possible to use the existing `labels_textlabel`. But at the current implementation there is no way to distinguish words that are entered for `tags` question, from words that are entered for `impressions` question. Ultimately it is up to BE how to store the data, I'm just pointing out that some modification may be needed to distinguish `tags` and `impressions` 😅 
2. The thing is, the labels Radość, Szczęście, Zachwyt, Podziw, Duma, ... are also scaled (e.g. Radość: 95, Podziw: 10, ...), and we also need to store the values for the labels somehow. So I suppose the values will be stored in table `label_type_scaletype` you mentioned. Well, I am fine with that. XD

**Comment by teddy-f-47** [comment]
@haanh764 btw, the groups "Offensiveness" and "Humor" also include some textfield inputs, so if you want to store these texts in the existing `labels_textlabel`, an additional field in the table will be needed to distinguish if a label belongs to `summary-tags`, `summary-impressions`, `others-Czego życzę autorowi tego tekstu`, `offensiveness-płec`, ..... and so on :D

**Comment by haanh764** [comment]
> @haanh764 btw, the groups "Offensiveness" and "Humor" also include some textfield inputs, so if you want to store these texts in the existing `labels_textlabel`, an additional field in the table will be needed to distinguish if a label belongs to `summary-tags`, `summary-impressions`, `others-Czego życzę autorowi tego tekstu`, `offensiveness-płec`, ..... and so on :D

Yeah I understand, in this case if we wanna use this strategy we can add a new table to keep the questions, maybe, like (question_id, question,..etc) and in the `labels_textlabel` we just need to reference the question_id XD

**Comment by teddy-f-47** [comment]
> 1. I wonder about this. This can be a solution; another way is to stringify them as JSON string and frontend can parse that. I think splitting them by their commas will be easier to handle, but ofc, this is for the BE to judge XD    And for the FE too, but I recall that the `summary` is not within my area, or did I remember it wrong?
> 2. Yes, I agree with this.
> 3. I can't really agree with that. I think its better to store it as true or false; I know the negative statement (nie wiem) may bother you but storing it as null won't be good either since null usually means that the field has no data, if I understood the value correctly :)
> 4. Yes, I agree with this.

1. Yeah, summary is my task, I'm just asking because the other metacategory groups also contain textfield inputs XD
3. Okay.... initially I thought that for example we have `Wulgarny [Wcale --------------- W pełni] [Checkbox: Nie wiem]`, if the checbox nie wiem is marked then the data stored will be something like: `wulgarny: null` because I thought it is somewhat important to distinguish between when someone answers 0 and not giving any answer. But we can also just treat it as `wulgarny: 0`.

**Comment by haanh764** [comment]
> > > 
> > 
> > 
> > About the label types, I have some ideas also so we can consider XD
> > 
> > 1. About the Summary mode, it will be the textfiled input so I think we can do it like in the Seq2Seq project because it's pretty the same thing. There's a text filed and we can type what ever want and then enter, and then type another thing and enter. You can check table `labels_textlabel`. For eg, here `example_id = 508380` has few label as the text input from textfield:
> >    Screenshot from 2022-09-27 10-44-34
> > 2. For the other modes which have Labels (likes Radość, szczęście, Zachwyt, podziw, duma, Pozytywne, Negatywne,...etc), we can just use the current table `label_types_categorytype`, because basically the characteristic of them are pretty the same. They are just the categories, and they are already map with example by example_id, and label_id via table `labels_category`. The only thing we need to do is somehow init all of the polish categories in the database on starting the program if there are no those labels. And if the project is in type of Affective Annotation it will use these labels automatically
> >    Screenshot from 2022-09-27 10-54-28
> > 3. The modes using scale, I think we can create a new table for keeping the scale categories, for eg `label_type_scaletype` which keep the scale labels
> 
> 1. I see, for the Summary mode, it is possible to use the existing `labels_textlabel`. But at the current implementation there is no way to distinguish words that are entered for `tags` question, from words that are entered for `impressions` question. Ultimately it is up to BE how to store the data, I'm just pointing out that some modification may be needed to distinguish `tags` and `impressions` sweat_smile
> 2. The thing is, the labels Radość, Szczęście, Zachwyt, Podziw, Duma, ... are also scaled (e.g. Radość: 95, Podziw: 10, ...), and we also need to store the values for the labels somehow. So I suppose the values will be stored in table `label_type_scaletype` you mentioned. Well, I am fine with that. XD

about 2, yeah the table `label_type_scaletype` is for keeping the scale value, I think it will be clearer if we keep the label separately like the current mechanism of doccano. But I'm oke with create new tables for each kind of mode also, just in this case in 1 table we will have many type of labels XD But I'm oke with both XD So what do you think

**Comment by haanh764** [comment]
> > 1. I wonder about this. This can be a solution; another way is to stringify them as JSON string and frontend can parse that. I think splitting them by their commas will be easier to handle, but ofc, this is for the BE to judge XD    And for the FE too, but I recall that the `summary` is not within my area, or did I remember it wrong?
> > 2. Yes, I agree with this.
> > 3. I can't really agree with that. I think its better to store it as true or false; I know the negative statement (nie wiem) may bother you but storing it as null won't be good either since null usually means that the field has no data, if I understood the value correctly :)
> > 4. Yes, I agree with this.
> 
> 1. Yeah, summary is my task, I'm just asking because the other metacategory groups also contain textfield inputs XD
> 2. Okay.... initially I thought that for example we have `Wulgarny [Wcale --------------- W pełni] [Checkbox: Nie wiem]`, if the checbox nie wiem is marked then the data stored will be something like: `wulgarny: null` because I thought it is somewhat important to distinguish between when someone answers 0 and not giving any answer. But we can also just treat it as `wulgarny: 0`.

I also think that it's good to distinguish between False and 0-scale, maybe we can treat nie wiem as -1, -999 or something else which is not null but no answer XD

**Comment by artikandri** [comment]
> > 1. I wonder about this. This can be a solution; another way is to stringify them as JSON string and frontend can parse that. I think splitting them by their commas will be easier to handle, but ofc, this is for the BE to judge XD    And for the FE too, but I recall that the `summary` is not within my area, or did I remember it wrong?
> > 2. Yes, I agree with this.
> > 3. I can't really agree with that. I think its better to store it as true or false; I know the negative statement (nie wiem) may bother you but storing it as null won't be good either since null usually means that the field has no data, if I understood the value correctly :)
> > 4. Yes, I agree with this.
> 
> 1. Yeah, summary is my task, I'm just asking because the other metacategory groups also contain textfield inputs XD
> 2. Okay.... initially I thought that for example we have `Wulgarny [Wcale --------------- W pełni] [Checkbox: Nie wiem]`, if the checbox nie wiem is marked then the data stored will be something like: `wulgarny: null` because I thought it is somewhat important to distinguish between when someone answers 0 and not giving any answer. But we can also just treat it as `wulgarny: 0`.

1. Then I will agree on using commas to separate it, but I havent checked the current implementation, if there was already an existing implementation we can refer to that I think XD no need to reinvent 
2. I agree with Anh on this, -1 is better than null.

**Comment by teddy-f-47** [comment]
> > > > 
> > > 
> > > 
> > > About the label types, I have some ideas also so we can consider XD
> > > 
> > > 1. About the Summary mode, it will be the textfiled input so I think we can do it like in the Seq2Seq project because it's pretty the same thing. There's a text filed and we can type what ever want and then enter, and then type another thing and enter. You can check table `labels_textlabel`. For eg, here `example_id = 508380` has few label as the text input from textfield:
> > >    Screenshot from 2022-09-27 10-44-34
> > > 2. For the other modes which have Labels (likes Radość, szczęście, Zachwyt, podziw, duma, Pozytywne, Negatywne,...etc), we can just use the current table `label_types_categorytype`, because basically the characteristic of them are pretty the same. They are just the categories, and they are already map with example by example_id, and label_id via table `labels_category`. The only thing we need to do is somehow init all of the polish categories in the database on starting the program if there are no those labels. And if the project is in type of Affective Annotation it will use these labels automatically
> > >    Screenshot from 2022-09-27 10-54-28
> > > 3. The modes using scale, I think we can create a new table for keeping the scale categories, for eg `label_type_scaletype` which keep the scale labels
> > 
> > 
> > 
> > 1. I see, for the Summary mode, it is possible to use the existing `labels_textlabel`. But at the current implementation there is no way to distinguish words that are entered for `tags` question, from words that are entered for `impressions` question. Ultimately it is up to BE how to store the data, I'm just pointing out that some modification may be needed to distinguish `tags` and `impressions` sweat_smile
> > 2. The thing is, the labels Radość, Szczęście, Zachwyt, Podziw, Duma, ... are also scaled (e.g. Radość: 95, Podziw: 10, ...), and we also need to store the values for the labels somehow. So I suppose the values will be stored in table `label_type_scaletype` you mentioned. Well, I am fine with that. XD
> 
> about 2, yeah the table `label_type_scaletype` is for keeping the scale value, I think it will be clearer if we keep the label separately like the current mechanism of doccano. But I'm oke with create new tables for each kind of mode also, just in this case in 1 table we will have many type of labels XD But I'm oke with both XD So what do you think

Initially I thought making a table for each mode will make it look better organized and easier to understand, but then again this is not a big deal because at the end the structure of the exported json is the most important thing regardless of the db organization. I think your approach of using existing tables plus just a few additional tables is easier to implement, and it conforms with the way doccano operates so far, so I think it is a better idea. XD

**Comment by teddy-f-47** [comment]
> I also think that it's good to distinguish between False and 0-scale, maybe we can treat nie wiem as -1, -999 or something else which is not null but no answer XD

Great idea! Agreed, so we will use -1 value when `nie wiem` is checked :D

**Comment by haanh764** [comment]
> > > > > 
> > > > 
> > > > 
> > > > About the label types, I have some ideas also so we can consider XD
> > > > 
> > > > 1. About the Summary mode, it will be the textfiled input so I think we can do it like in the Seq2Seq project because it's pretty the same thing. There's a text filed and we can type what ever want and then enter, and then type another thing and enter. You can check table `labels_textlabel`. For eg, here `example_id = 508380` has few label as the text input from textfield:
> > > >    Screenshot from 2022-09-27 10-44-34
> > > > 2. For the other modes which have Labels (likes Radość, szczęście, Zachwyt, podziw, duma, Pozytywne, Negatywne,...etc), we can just use the current table `label_types_categorytype`, because basically the characteristic of them are pretty the same. They are just the categories, and they are already map with example by example_id, and label_id via table `labels_category`. The only thing we need to do is somehow init all of the polish categories in the database on starting the program if there are no those labels. And if the project is in type of Affective Annotation it will use these labels automatically
> > > >    Screenshot from 2022-09-27 10-54-28
> > > > 3. The modes using scale, I think we can create a new table for keeping the scale categories, for eg `label_type_scaletype` which keep the scale labels
> > > 
> > > 
> > > 
> > > 1. I see, for the Summary mode, it is possible to use the existing `labels_textlabel`. But at the current implementation there is no way to distinguish words that are entered for `tags` question, from words that are entered for `impressions` question. Ultimately it is up to BE how to store the data, I'm just pointing out that some modification may be needed to distinguish `tags` and `impressions` sweat_smile
> > > 2. The thing is, the labels Radość, Szczęście, Zachwyt, Podziw, Duma, ... are also scaled (e.g. Radość: 95, Podziw: 10, ...), and we also need to store the values for the labels somehow. So I suppose the values will be stored in table `label_type_scaletype` you mentioned. Well, I am fine with that. XD
> > 
> > 
> > about 2, yeah the table `label_type_scaletype` is for keeping the scale value, I think it will be clearer if we keep the label separately like the current mechanism of doccano. But I'm oke with create new tables for each kind of mode also, just in this case in 1 table we will have many type of labels XD But I'm oke with both XD So what do you think
> 
> Initially I thought making a table for each mode will make it look better organized and easier to understand, but then again this is not a big deal because at the end the structure of the exported json is the most important thing regardless of the db organization. I think your approach of using existing tables plus just a few additional tables is easier to implement, and it conforms with the way doccano operates so far, so I think it is a better idea. XD

Okie so I will try to implement the db on that way, and we can think about the export format also XD I havent thought about it haha XD

**Pull request merged**
