### PR TITLE
feat: UI fixes and adjustments

### PR DESCRIPTION
**Pull request by teddy-f-47**
Issues solved with this PR:
 1. Make PL as default language (Unified language after finish questionnaire - change to annotation view)
 2. Remove the information before each questionnaire, show it only once
 3. Remove title of questionnaire
 4. Finish accept button - "ZAKOŃCZ"
 5. Change "Stan anotacji", "Rozpocznij anotację" button
 6. Razem tekstów, Zakończono tekstów
 7. Confirm button:  ZAAKCEPTUJ / ZAAKCEPTOWANE
 8. Show end-of-research questionnaire after 3 months without the need to finish all projects
 9. Translate clear annotation button's message
 10. Rzekonania -> Przekonania
 11. Uppercase first letters (Absurd, Humor.., Humor..)
 12. String adjustments in questionnaires as commented in gdocs
 13. Make a sticky legend on top right corner of questionnaire if the questionnaire contains scale-based questions

What's changed:
 - frontend/components/example/ArticleList.vue : Make button label exactly the same as the translation string (only capitalized on first letter)
 - frontend/components/layout/TheSideBar.vue : Make button label exactly the same as the translation string (only capitalized on first letter)
 - frontend/components/questionnaires/QuestionnaireForm.vue : Remove greeting message, add sticky card containing scale legend
 - frontend/components/tasks/toolbar/forms/FormClearLabel.vue : Add translated message
 - frontend/components/utils/ActionMenu.vue : Make button label exactly the same as the translation string (only capitalized on first letter)
 - frontend/i18n/* : Add translations and adjust words, capitalization
 - frontend/middleware/check-questionnaire.js : Change default locale value to pl
 - frontend/pages/projects/_id/dataset/import.vue : Add locale path to router push
 - frontend/pages/projects/_id/dataset/index.vue : Add locale path to router push, make button label exactly the same as the translation string (only capitalized on first letter)
 - frontend/pages/projects/_id/labels/_label_id/edit.vue : Add locale path to router push
 - frontend/pages/projects/_id/labels/add.vue : Add locale path to router push
 - frontend/pages/projects/_id/labels/import.vue : Add locale path to router push
 - frontend/pages/projects/_id/labels/index.vue : Add locale path to router push
 - frontend/pages/projects/_id/members/index.vue : Add locale path to router push
 - frontend/pages/projects/create.vue : Add locale path to router push
 - frontend/pages/questionnaires/przed_badaniem/js/questionnaires.js : Adjust question strings (won't affect mapping due to having headers)
 - frontend/pages/questionnaires/przed_i_po_badaniu/js/questionnaires.js : Remove some scale desc, put questions into one segment
 - frontend/utils/questionnaires.js : Make end-of-research questionnaires appear after 3 months without regards of completed projects

Screenshots:
Capitalization only first letter
ss10

Zaakceptuj/ Zaakceptowane, tekstów
ss2
ss3

Sticky scale legend, zakończ button label at the end
ss8
ss9

### CODE REVIEW

**Review by haanh764 — APPROVED** [review]
Hello, thank you so  much for your very quick fixes! I have tested and everything seems oke, so approved! Btw, I have a very minor comment that for some legend in questionnaire, since we put it stick to the top right corner, then is it needed to be in the description anymore (since they're duplicated)? So I think for not being waste time to adjust it again later, maybe we should confirm with dr Kocon to make sure XD

**Comment by teddy-f-47** [comment]
> Hello, thank you so much for your very quick fixes! I have tested and everything seems oke, so approved! Btw, I have a very minor comment that for some legend in questionnaire, since we put it stick to the top right corner, then is it needed to be in the description anymore (since they're duplicated)? So I think for not being waste time to adjust it again later, maybe we should confirm with dr Kocon to make sure XD

Honestly, I am thinking about this, and I am not sure..... I think I will ask him.

**Review by artikandri — APPROVED** [review]
Hello, the code looks fine, thank you for the good work! My comment is similar with Anh. I also need to comment about the `hasFinishedAll` attribute which should be removed in ideal situation, but lets keep it for future uses in case it will be necessary. Approved.

**Comment by teddy-f-47** [comment]
Hi all, so I have also removed the scale legend from inside the questionnaire. I also adjusted the message on the top of questionnaire a bit to reflect the fact that the scale legend is on the right (not bottom of it). In addition, I noticed that the sticky card appeared when there is no scale legend to show, so I have corrected the code so that the sticky card does not appear when not necessary.

ssA
ssB
ssC

**Pull request merged**
