### PR TITLE
Feat: FE -  sticky container

### PR DESCRIPTION
**Pull request by artikandri**
Features added with this PR: 
- Sticky annotation container

Hello, this PR is concerned with the request to make the annotation text sticky XD I hope I understand it correctly, so from my understanding, this is how I did it. Please comment on the approach or whether I understood the task correctly or not, thank you

What's changed: 
- `frontend/pages/projects/_id/affective-annotation/index.vue`: added styling to make container sticky

Screenshot: 
image

### CODE REVIEW

**Review by teddy-f-47 — APPROVED** [review]
Hello, I have checked the code and tested the app. I think everything is good and it is nicely done. Thank you for the nice work, approved! :)

**Review by haanh764 — APPROVED** [review]
Sorry for a bit late review :sweat_smile: Thank you so much for the great work. I have tested and everything works well! Approved!

**Comment by haanh764** [comment]
btw, there's a minor warning in the yarn dev about this ` warning  Attribute "class" should go before "@shortkey"  vue/attributes-order` XD it's pretty minor but can you check this before merging XD

**Comment by artikandri** [comment]
Sorry, I missed the comment about the warning :"))) I will make a PR for that, sorryyyy

**Pull request merged**
