### PR TITLE
feat: IsSingleAnnView fix, canConfirm check for the review button from the HumorInput and OffensiveInput components

### PR DESCRIPTION
**Pull request by artikandri**
What's changed: 
- `frontend/components/layout/TheSideBar.vue`: showing the annotation button in the sidebar when the project is not `affective annotation`
- `frontend/components/tasks/affectiveAnnotation/*/*.vue`: added `isChanged` and `isSubmitting` flags for `scales`, added `canConfirm` flag for the HumorInput and OffensiveInput. Now the user can only confirm when they have: 
--- Changed at least one of the sliders to any value. They may also confirm when they changed the slider to 0 again
--- If they have changed one of the sliders and they clicked one of the checkboxes, they can only confirm when they have filled the textbox under the checkbox, if they are present 
- `frontend/components/tasks/sequenceLabeling/EntityEditor.vue`: added the `readOnly` property, show the labeling menu only when its not in read only mode 
- `frontend/components/tasks/toolbar/buttons/ButtonPagination.vue`: remove the `jump` title
- `frontend/pages/projects/_id/affective-annotation/index.vue`: changed the `isSingleAnnView` check to `isAffectiveAnnotation` check; `canConfirm` check, removed unnecessary components
- `frontend/pages/projects/_id/dataset/index.vue`: disabled the `button` when the project has no items

Screenshots: 
image
image

### CODE REVIEW

**Review by haanh764 — COMMENTED** [review]
Hello, thank you for your nice work! I've checked but I think the validation still doesn't match the requirement. For the Humor and Offensive mode, the requirement is `if there is "0" on two sliders before, user does not need to click on one of the checkboxes here; otherwise - he must click on at least one`
Currently, there're 2 points I'm concerning:
- (1) When I choose scale on 2 sliders, then I can click to the Confirm button. But, as the requirement, if the values on these 2 sliders are not 0, I have to choose at least 1 checkbox below, then I can confirm it. So I think you should add 1 more condition on this validation.
- (2) Currently, I can't confirm if I dont choose anything on these 2 sliders. But as the requirement, I understand that I can select 0 on these 2 sliders if I really have no feeling about humor/offensive, and if it's 0 I can just confirm without choosing the below checkbox. Also currently, I can't choose 0 on the sliders :sweat_smile: Actually I can, but I have to slide it a bit to another value then slide it back to 0, which is very uncomfortable and not a good user experience (?) So what do you think?

**Comment by artikandri** [comment]
> Hello, thank you for your nice work! I've checked but I think the validation still doesn't match the requirement. For the Humor and Offensive mode, the requirement is `if there is "0" on two sliders before, user does not need to click on one of the checkboxes here; otherwise - he must click on at least one` Currently, there're 2 points I'm concerning:
> 
> * (1) When I choose scale on 2 sliders, then I can click to the Confirm button. But, as the requirement, if the values on these 2 sliders are not 0, I have to choose at least 1 checkbox below, then I can confirm it. So I think you should add 1 more condition on this validation.
> * (2) Currently, I can't confirm if I dont choose anything on these 2 sliders. But as the requirement, I understand that I can select 0 on these 2 sliders if I really have no feeling about humor/offensive, and if it's 0 I can just confirm without choosing the below checkbox. Also currently, I can't choose 0 on the sliders sweat_smile Actually I can, but I have to slide it a bit to another value then slide it back to 0, which is very uncomfortable and not a good user experience (?) So what do you think?

1. Hello, thank you for pointing it out! I missed that requirement XD  I have added the validation, can you check it XD
2. Actually you can, but its not very clear because the slider thumb is always there XD so now I have modified mine like Teddy's so that the slider thumb won't be visible unless it's clicked.

**Review by teddy-f-47 — COMMENTED** [review]
Hello! I have seen the code and tested the app. I think it works fine and everything is ok. XD

Unfortunately, I just checked the gdoc containing the requirements, and there are some additional dimensions in the Humor mode:
Charakter humoru, śmieszy ze względu na:
 - absurd [Checkbox]
 - humor sytuacyjny [Checkbox]
 - humor patetyczny [Checkbox]
I'm not sure when these new dimensions were added to the gdoc, as I've just seen it now as well. Nevertheless, I think we need to add them to doccano 😅 In Offensive mode, I think there is no change, so it is fine so far.

edit: Also I see that your approach is directly disabling the "confirm as done" button, to prevent confirming unfinished annotations. I think it is fine, but you can also use the alert I added in the previous PR. It is up to you 😅 and just a reminder to solve the conflict after the recent merge :)

**Comment by haanh764** [comment]
Hello, I have tested your changes and I think it's oke now XD 
About the new dimension added in the gdoc I think we can just add it, probably he forgot to remind us about the changes :sweat_smile: 

btw, just my opinion, I think it's better to be uniformed because it'll be a bit weird if sometimes there's alert and sometimes not, especially when we have the combination mode (the mode that combine all 5 annotation modes together) :sweat_smile: but it's up to fe side XD

**Comment by artikandri** [comment]
Hello, thank you for pointing out about the changes in the doc and also the difference in behavior. About the doc, I don't know when it was added as well, but I will add it later. As for the behavior, this PR was made before the previous PR was merged, so of course the change introduced in the previous PR (the alert)  was not integrated  :)   I will work on them later and fix the conflicts.

**Comment by artikandri** [comment]
Hello everyone, I have added the new dimensions as well as removed the disabled property and used the alert instead. I also adjusted the alert conditions a bit XD can you check 

image

**Review by teddy-f-47 — APPROVED** [review]
Hello, I have tested the app once again, and I think it works fine on my machine. Thank you for your great work, approved for merging! :)

**Review by haanh764 — APPROVED** [review]
Hello, thank you for you great work again XD I have tested and everything works fine. Approved XD

**Pull request merged**
