### PR TITLE
feat: added article viewer 

### PR DESCRIPTION
**Pull request by artikandri**
What's changed: 
- `frontend/pages/projects/_id/article-annotation/index.vue`:  imported the article viewer 

What's new: 
- `frontend/components/tasks/toolbar/ToolbarArticle.vue`: new toolbar to view the whole article 

Notable: 
- I moved back the article title to the top, I think it looks tidier that way XD  what do you think
- I sorted the article content according to their order by using the `orderBy` function from lodash, and it seems like it shows a new bug in which the next item given by the BE doesnt match the one given in the article viewer XD     this happens when a dataset is uploaded twice. 

Screenshots: 
image

### CODE REVIEW

**Comment by teddy-f-47** [comment]
Hi! Thank you very much for your excellent work! I have tested it and the functionality is working fine as expected.

About your mentioned new bug, I am unable to reproduce it. I tried uploading the same file 3x and the texts seemed to be consistent on the left and right side. In the following recording I also tried uploading the same file 3x as well with the same article_id and order values, I just changed the texts prior to uploading to make it easier to track:

https://user-images.githubusercontent.com/64476430/191543353-cd897a33-5a45-497b-8c27-5b8d591bae01.mp4

But maybe I missed something, so please point it out if it is the case XD

About the code, it definitely works, but I just have a minor question because the ToolbarArticle is throwing some errors:
sssss
Is there any way to remove these errors? Because the functionality seems to be working just fine XD

Edit:
I think we can remove some of the errors by adding the return type to the computed property, like:
```
  computed: {
    itemPosition(): number {
      return this.articleItems.findIndex((item : object) => item.id 
        === this.currentArticleItem.id ) + 1
    }
  },
```
I managed to remove some errors with it, but I still get one error `Type 'unknown' is not assignable to type 'object'` XD

**Comment by teddy-f-47** [comment]
After some googling, I finally managed to remove all errors by adding the return type as number and changing the type of `item` to `any`:
```
  computed: {
    itemPosition(): number {
      return this.articleItems.findIndex((item : any) => item.id 
        === this.currentArticleItem.id ) + 1
    }
  },
```

But I am not experienced with vue and typescript, so I'm not sure if this is a safe solution XD

**Comment by artikandri** [comment]
> After some googling, I finally managed to remove all errors by adding the return type as number and changing the type of `item` to `any`:
> 
> ```
>   computed: {
>     itemPosition(): number {
>       return this.articleItems.findIndex((item : any) => item.id 
>         === this.currentArticleItem.id ) + 1
>     }
>   },
> ```
> 
> But I am not experienced with vue and typescript, so I'm not sure if this is a safe solution XD

Sorry, the error didnt appear on my place but I will try to reproduce it XD It's related to Typescript's  typesafe functionality, which is very useful to handle future errors because it prevents the system from returning undefined and null.. but they are annoying for sure XD    Thank you for pointing it out.

**Comment by artikandri** [comment]
> After some googling, I finally managed to remove all errors by adding the return type as number and changing the type of `item` to `any`:
> 
> ```
>   computed: {
>     itemPosition(): number {
>       return this.articleItems.findIndex((item : any) => item.id 
>         === this.currentArticleItem.id ) + 1
>     }
>   },
> ```
> 
> But I am not experienced with vue and typescript, so I'm not sure if this is a safe solution XD

I have implemented this approach and it works well, thank you! Sometimes the typescript linter doesnt always work which is why this error got pushed, sorry for the trouble.

**Comment by teddy-f-47** [comment]
No problem XD I think everything is fine now. About the possible bug when having the same file uploaded multiple times, at least on my machine it didn't happen, so I'm not sure about the possible cause.... I give my approval now, imo it is fine to merge it. XD

Also I remember an additional requirement, to mark texts that have been annotated&confirmed with green font/background. But the current implementation is already much more than good enough for progress demo, so let's leave the green mark for the next PR 😅 

Thank you for the great work!

**Review by teddy-f-47 — APPROVED** [review]

**Comment by artikandri** [comment]
To implement that, I think I would need an additional change from BE since currently the example api doesnt return the annotation info, and how else would I know whether its already annotated or not, passed it doesnt mean I have annotated it right, I might have just skipped it  xD   I probably can request an api for every item but I dont thinks thats a good approach. I will merge this for now, thank you!

**Comment by teddy-f-47** [comment]
> To implement that, I think I would need an additional change from BE since currently the example api doesnt return the annotation info, and how else would I know whether its already annotated or not, passed it doesnt mean I have annotated it right, I might have just skipped it xD I probably can request an api for every item but I dont thinks thats a good approach. I will merge this for now, thank you!

Hello, I also thought this is the case, but I just checked the list of returned data from the api and it actually includes `is_confirmed` (on FE in ExampleDTO the field is available as `isConfirmed`), which is a boolean field indicating if the user has confirmed their annotation (i.e. has clicked the first button in the toolbar). I think we can do the green marking based on this `isConfirmed` value. XD

**Comment by artikandri** [comment]
> > To implement that, I think I would need an additional change from BE since currently the example api doesnt return the annotation info, and how else would I know whether its already annotated or not, passed it doesnt mean I have annotated it right, I might have just skipped it xD I probably can request an api for every item but I dont thinks thats a good approach. I will merge this for now, thank you!
> 
> Hello, I also thought this is the case, but I just checked the list of returned data from the api and it actually includes `is_confirmed` (on FE in ExampleDTO the field is available as `isConfirmed`), which is a boolean field indicating if the user has confirmed their annotation (i.e. has clicked the first button in the toolbar). I think we can do the green marking based on this `isConfirmed` value. XD

And about this I wonder xD isConfirmed is to be set true when the annotation is already approved right? But what does it mean to be annotated? Do we need approval to say that a text is already annotated or not? 
The green color itself is easy but I'm just wondering about this xD

**Comment by teddy-f-47** [comment]
> > > To implement that, I think I would need an additional change from BE since currently the example api doesnt return the annotation info, and how else would I know whether its already annotated or not, passed it doesnt mean I have annotated it right, I might have just skipped it xD I probably can request an api for every item but I dont thinks thats a good approach. I will merge this for now, thank you!
> > 
> > 
> > Hello, I also thought this is the case, but I just checked the list of returned data from the api and it actually includes `is_confirmed` (on FE in ExampleDTO the field is available as `isConfirmed`), which is a boolean field indicating if the user has confirmed their annotation (i.e. has clicked the first button in the toolbar). I think we can do the green marking based on this `isConfirmed` value. XD
> 
> And about this I wonder xD isConfirmed is to be set true when the annotation is already approved right? But what does it mean to be annotated? Do we need approval to say that a text is already annotated or not? The green color itself is easy but I'm just wondering about this xD

I have turned off my laptop so I can't check it now, but if I remember correctly there are `isConfirmed` and `isApproved` (or isApprovedBy, don't remember precisely) fields.

isConfirmed means that the user has clicked the "checked" button, confirming that they consider the annotation for the given text is done. Currently, the implementation of the progress bar is based on isConfirmed, so I think the green marking on viewer component should be done in a similar way based on isConfirmed.

isApproved indicates whether the annotation has been approved by admin / superuser, but this value is only used in the exporting mechanism (there is a checkbox to export annotations that have been approved only, if I remember correctly).... :D

**Comment by artikandri** [comment]
> > > > To implement that, I think I would need an additional change from BE since currently the example api doesnt return the annotation info, and how else would I know whether its already annotated or not, passed it doesnt mean I have annotated it right, I might have just skipped it xD I probably can request an api for every item but I dont thinks thats a good approach. I will merge this for now, thank you!
> > > 
> > > 
> > > Hello, I also thought this is the case, but I just checked the list of returned data from the api and it actually includes `is_confirmed` (on FE in ExampleDTO the field is available as `isConfirmed`), which is a boolean field indicating if the user has confirmed their annotation (i.e. has clicked the first button in the toolbar). I think we can do the green marking based on this `isConfirmed` value. XD
> > 
> > 
> > And about this I wonder xD isConfirmed is to be set true when the annotation is already approved right? But what does it mean to be annotated? Do we need approval to say that a text is already annotated or not? The green color itself is easy but I'm just wondering about this xD
> 
> I have turned off my laptop so I can't check it now, but if I remember correctly there are `isConfirmed` and `isApproved` (or isApprovedBy, don't remember precisely) fields.
> 
> isConfirmed means that the user has clicked the "checked" button, confirming that they consider the annotation for the given text is done. Currently, the implementation of the progress bar is based on isConfirmed, so I think the green marking on viewer component should be done in a similar way based on isConfirmed.
> 
> isApproved indicates whether the annotation has been approved by admin / superuser, but this value is only used in the exporting mechanism (there is a checkbox to export annotations that have been approved only, if I remember correctly).... :D

Thanks for the explanation, I have added it and made the PR XD please check: https://github.com/CLARIN-PL/doccano/pull/24

**Pull request merged**
